### ISSUE TITLE
Can not get Githoard to find repository with Git URL

### ISSUE THREAD

**Issue by nicojdejong** [beepboopbangbang/githoard#6]
I tried all sorts of Git Urls (full and relative) but the response remains no Repositories found (I have nothing in my clone directory, but expected to add those trough finding the repositories online. Maybe firewall settings? I did not change anyhing upon installing on Windows 10.

**Comment by jojobyte** [comment]
Try pasting `https://github.com/jojobyte/githoard.git` inside the URL/Search Bar then hit enter/return on your keyboard.

If you are trying to search the internet via the URL/Search Bar it wont work. Currently, it only searches repositories cloned by GitHoard, although this may change in the future.

If you can share a screenshot/gif of what you're trying to do that would also help with debugging.

**Comment by yannduran** [comment]
I was reading this issue, and thought I'd give what you suggested to @nicojdejong. Below is the error dialog that poppedup:
 
![2018-05-16_09-14-32](https://user-images.githubusercontent.com/2031126/40088637-38c47c4e-58eb-11e8-92d5-6fd78c7016c0.png)

It did however proceed to clone the repo. HTH

**Comment by jojobyte** [comment]
This should be fixed by #9
