### ISSUE TITLE
Suggestion: Namespacing based on git hosting server name

### ISSUE THREAD

**Issue by karuppiah7890** [beepboopbangbang/githoard#7]
I am managing and checking projects in github and gitlab. I am sure many people would be using bitbucket and others too. 

Currently from what I can see, GitHoard takes a single `clone directory`, and clones all the repositories there (regardless of git hosting service). I think it would be helpful to clone inside namespaced directories in this `clone directory`, with namespaces being the git hosting service, example `github.com` or just `github`, then `gitlab` and so on. The directory tree will look something like this, given a namespace :

<img width="573" alt="screen shot 2018-08-16 at 9 47 40 am" src="https://user-images.githubusercontent.com/12808424/44186859-743a8480-a139-11e8-91be-9a18809c9898.png">

and GitHoard can store in the given `clone directory` one level deep, under namespace based on git clone url. What do you think about this idea @jojobyte ? I just thought it might be easier to manage things across hosting services, and also, a free advantage of this is - we can avoid name conflicts if any. Just a thought. If you think this is good, I can even try to contribute and raise a PR. I just wanted to discuss this before doing anything 😄

**Comment by jojobyte** [comment]
Sorry for not responding to this. Totally missed it.

This feature is something that was planned for when this project was started. Currently, working on a complete re-code of GitHoard, and this will hopefully be included as one of the new features.

Ideally, you'd be able to define your directory structure in the settings. It would either be an upgraded clone directory field or a separate directory structure field where you could define things based on variables like...

`{{source}}/{{owner}}/{{repo}}` or `{{site}}/{{owner}}/{{repo}}` etc.
